version: "3"
services:
  api:
    image: demo_api
    deploy:
      replicas: 3
    ports:
      - "9999:8080"
  db:
    image: mysql:8
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=hello
      - MYSQL_USER=somkiat
      - MYSQL_PASSWORD=pass
    
  