FROM openjdk:11.0.14.1-jdk-slim-bullseye as step1
WORKDIR /build
COPY . .
RUN ./mvnw clean package

FROM openjdk:11.0.14.1-jre-slim-bullseye
WORKDIR /deploy
COPY --from=step1 /build/target/*.jar ./app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
