version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:8080"
    depends_on:
      - "db"
    command: [ "./wait-for-it.sh", "db:3306", "--", "java", "-jar", "app.jar" ]
  db:
    image: mysql:8
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=hello
      - MYSQL_USER=somkiat
      - MYSQL_PASSWORD=pass
    volumes:
      - ./data/tables.sql:/docker-entrypoint-initdb.d/1.sql
    
  