version: "3"
services:
  db:
    image: mysql:8
    container_name: db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=hello
      - MYSQL_USER=somkiat
      - MYSQL_PASSWORD=pass
    volumes:
      - ./data/tables.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - "3306:3306"
    
  