apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: somkiat/java-api:1.0
          resources:
            requests:
              memory: "600Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080