apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30020
  type: NodePort
  selector:
    app: api